services:
  krakend:
    image: devopsfaith/krakend
    container_name: krakend
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "8082:8082"
      - "9091:9091"
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
      - ./keys.json:/etc/krakend/keys.json
      - ./lua:/etc/krakend/lua
    command: run -c /etc/krakend/krakend.json
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_AUTH_ANONYMOUS_ENABLED=true          # login istemeden görüntülemek için
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./grafana/datasource:/etc/grafana/provisioning/datasources


  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-data:/vault/data
      - ./vault:/vault/config
    entrypoint: vault
    command: server -config=/vault/config/vault-config.hcl
