spring.application.name=demo

spring.config.import=vault://
spring.cloud.vault.uri=http://vault:8200
spring.cloud.vault.token=

spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.default-context=demo

security.jwt.expiration-time=60000
security.jwt.refresh-expiration-time=604800000

##########################
soap.services.country.wsdl=http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?WSDL
soap.services.country.serviceClass=org.oorsprong.websamples_countryinfo.CountryInfoService
soap.services.country.portMethod=getCountryInfoServiceSoap

soap.services.number.wsdl=https://www.dataaccess.com/webservicesserver/numberconversion.wso?WSDL
soap.services.number.serviceClass=com.dataaccess.webservicesserver.NumberConversion
soap.services.number.portMethod=getNumberConversionSoap

soap.services.temperature.wsdl=https://www.w3schools.com/xml/tempconvert.asmx?WSDL
soap.services.temperature.serviceClass=https.www_w3schools_com.xml.TempConvert
soap.services.temperature.portMethod=getTempConvertSoap

soap.services.isbn.wsdl=http://webservices.daehosting.com/services/isbnservice.wso?WSDL
soap.services.isbn.serviceClass=com.daehosting.webservices.\u0131sbn.ISBNService
soap.services.isbn.portMethod=getISBNServiceSoap

soap.services.calculator.wsdl=http://www.dneonline.com/calculator.asmx?WSDL
soap.services.calculator.serviceClass=org.tempuri.Calculator
soap.services.calculator.portMethod=getCalculatorSoap

soap.services.users.wsdl=http://localhost:8080/ws/UsersService.wsdl
soap.services.users.serviceClass=com.example.users.UsersService
soap.services.users.portMethod=getUsersPort

soap.services.products.wsdl=http://localhost:8080/ws/ProductsService.wsdl
soap.services.products.serviceClass=com.example.products.ProductsService
soap.services.products.portMethod=getProductsPort
##########################


spring.datasource.url=jdbc:mysql://host.docker.internal:3306/dbname
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always

products.datasource.url=jdbc:mysql://host.docker.internal:3306/dbname2
products.datasource.username=
products.datasource.password=
products.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


