spring.application.name=demo

security.jwt.secret-key=nVmlOnbi4DrkBHewkH95FvVYAmtpW2jkU706VYCcQAoObFb_icStV9mbepsr6fFc
security.jwt.expiration-time=28800000

soap.services.country.wsdl=http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?WSDL
soap.services.country.serviceClass=org.oorsprong.websamples_countryinfo.CountryInfoService
soap.services.country.portMethod=getCountryInfoServiceSoap

soap.services.number.wsdl=https://www.dataaccess.com/webservicesserver/numberconversion.wso?WSDL
soap.services.number.serviceClass=com.dataaccess.webservicesserver.NumberConversion
soap.services.number.portMethod=getNumberConversionSoap

soap.services.temperature.wsdl=https://www.w3schools.com/xml/tempconvert.asmx?WSDL
soap.services.temperature.serviceClass=https.www_w3schools_com.xml.TempConvert
soap.services.temperature.portMethod=getTempConvertSoap

soap.services.isbn.wsdl=http://webservices.daehosting.com/services/isbnservice.wso?WSDL
soap.services.isbn.serviceClass=com.daehosting.webservices.\u0131sbn.ISBNService
soap.services.isbn.portMethod=getISBNServiceSoap

soap.services.calculator.wsdl=http://www.dneonline.com/calculator.asmx?WSDL
soap.services.calculator.serviceClass=org.tempuri.Calculator
soap.services.calculator.portMethod=getCalculatorSoap



spring.datasource.url=jdbc:mysql://localhost:3306/xmldatabase
spring.datasource.username=hmmm
spring.datasource.password=hmmmm
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


